name: Cypress Tests run on Deploy from Main, on dev enviornment

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Copy dev env file
        run: cp .env.dev .env  

      - name: Run Cypress tests (headless)
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:run:dev
